### ISSUE TITLE
fxmanifest.lua failing.

### ISSUE THREAD

**Issue by SerenaKing** [JaredScar/Bad-Scoreboard#5]
Hey! 

I Downloaded this script today but the server was parsing this error.
`Could not parse resource metadata file resources//[Discord]/Bad-Scoreboard/fxmanifest.lua: ...games/resources//[Discord]/Bad-Scoreboard/fxmanifest.lua:16: '}' expected (to close '{' at line 14) near '"server.lua"'`

When looking I realized that there was a missing COMMA (,) in the file. Since I am to dumb to create a pull request I thought I do let you know here. So this would be the fix I guess.

```
fx_version 'cerulean'
game 'gta5'

author 'JaredScar'
description 'Fivem scoreboard'
version '1.6'
url 'https://github.com/JaredScar/Bad-Scoreboard'

client_scripts {
	"config.lua",
	'client.lua'
}

server_scripts { 
	"config.lua",
	"server.lua"
}

ui_page "NUI/panel.html"
files {
	"NUI/panel.js",
	"NUI/panel.html",
	"NUI/panel.css",
}
```

- Best Regards! 

Love your scripts ❤️

**Comment by JaredScar** [comment]
Oh wow.... Surprised no one ever made such a pull request. Fixing this now, thank you!
