### ISSUE TITLE
Scoreboard avatars not appearing.

### ISSUE THREAD

**Issue by SerenaKing** [JaredScar/Bad-Scoreboard#6]
# Introduction to my issue
So since I installed the script I didn't think much of it it loaded perfectly fine and easy to set-up even without guide. But then I published it to my main server and soon enough reports of it "Not working" came through. The screenshot below shows what is generally happening. It _should_ be displaying the images of the user. (I don't know why it can't since it has the permissions is on top of the member list & does it for the first user that joins) I generally don't know what I did wrong. (Well besides the `,` issue that we found out before).

# What is happening
The 1st attachment is what happens the when the 1st player joins (Server ID 1) But when more players join (Server ID 2+) it will just not load their avatars. But when the 1st player returns to the server (leaves & rejoins at any time) It will load their avatar perfectly fine.

# Fixes I tried
- I tried to use either of 2 of the oneSync settings
- I tried using no oneSync Setting
- I updated to the latest version (I had a outdated one for some reason)
- Reinstall the resource.

# Ending
I generally am lost. I seen the post on the forums > [here](https://forum.cfx.re/t/release-bad-scoreboard-possibly-the-best-fivem-server-scoreboard-scoreboard-works-with-onesync-infinity/1389564) < That more people have this issue. But no one has bothered to request actual support. I will do my best to come up with a fix and help around where I can. Sorry if I'm overloading you.

Thanks for looking into my previous issue to! 
Love your scripts keep it up! ❤️

Hope we can find the issue and resolve it!

![image](https://user-images.githubusercontent.com/84972623/134058145-eb54b3d4-76c0-48fe-b7e7-8fca9e62c307.png) 
![image](https://user-images.githubusercontent.com/84972623/134058709-6376672b-ed58-471e-ae19-5950354f2f42.png)

**Comment by JaredScar** [comment]
Is Badger_Discord_API up to date?

**Comment by SerenaKing** [comment]
Yes it is. This is the list of scripts that I am using related to your API. They are also all updated.

Badger_Discord_API
BadgerTools-Revamped
Badssentials (Modified version)
DiscordAcePerms
DiscordChatRoles

& Guardian all-though I am not sure that is one of yours.

**Comment by JaredScar** [comment]
I am pretty sure your Badger_Discord_API is outdated because I knew about a similar issue regarding this versions ago. I advise updating to the latest version of Badger_Discord_API and the problem should be fixed.

**Comment by SerenaKing** [comment]
After updating again. Yes that was the issue. `Badger_Discord_API` was outdated.
